# Site settings
title: JayCai's Blog
SEOTitle: JayCai's Blog | JayCai Blog
header-img: img/home-bg.jpg
email: jaycai96@gmail.com
description: "关于程序与设计、咖啡与摄影 | 这里是 @jaycai96 的个人博客。"
keyword: "jaycai96, @jaycai96,JayCai's Blog, 博客, 个人网站, 互联网, Web, Spark, Python, 数据分析, 机器学习"
url: "https://jaycai96.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     uc15007422
#zhihu_username:     jaycai96
github_username:    jaycai96
twitter_username:   jaycai96
#facebook_username:  jaycai96
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: jaycai96

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "神即道，道法自然，如来。"
sidebar-avatar: /img/avatar-jay.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Links
links: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "databricks",
        href: "https://databricks.com/blog/category/engineering/spark"
    },{
        title: "InfoQ",
        href: "https://www.infoq.cn/"
    },{
        title: "hongjiang(Scala)",
        href: "http://hongjiang.info/category/programming/scala/"
    },{
        title: "深度学习笔记",
        href: "http://www.ai-start.com/dl2017/"
    }
]
